language: java
jdk:
  - oraclejdk7
  - openjdk7
env:
  - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres SENDGRID_USERNAME=fake SENDGRID_PASSWORD=fake PORT=22777
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - pip install --user codecov
after_success:
  - codecov
notifications:
  slack:
    rooms:
      - cineweb:tKfEusk2qVyLPsv9rRbApttC#services