language: java
jdk:
  - oraclejdk7
  - openjdk7
env: DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
notifications:
  slack:
    rooms:
      - cineweb:tKfEusk2qVyLPsv9rRbApttC#services
